---
- name: Check if monit log file exists
  stat: 
    path: /var/log/monit.log
  register: log_file

- name: Create monit log file
  file:
    path: /var/log/monit.log
    state: touch
    owner: root
    group: root
    mode: '0755'
  when: not log_file.stat.exists

- name: Ensure required monit dirs exists
  file:
    path: "{{ item.path }}"
    state: "{{ item.state }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
  with_items:
    - path: /var/log/monit.log
      state: file
      mode: '0755'
    - path: /etc/monit
      state: directory
      mode: '0600'
    - path: /etc/monit/conf.d
      state: directory
      mode: '0600'
    - path: /var/lib/monit
      state: directory
      mode: '0755'

- name: Copy init script
  copy:
    src: monit-init
    dest: /etc/init.d/monit
    owner: root
    group: root
    mode: '0755'

- name: Copy monit defaults file
  copy:
    src: monit
    dest: /etc/default/monit
    owner: root
    group: root
    mode: '0600'
  notify: monit reload

- name: Build and copy main monit config file
  template:
    src: monitrc.j2
    dest: /etc/monit/monitrc
    owner: root
    group: root
    mode: '0600'
  notify: monit reload

- name: Link monitorc
  file:
    src: /etc/monit/monitrc
    dest: /etc/monitrc
    state: link
  notify: monit reload

- name: Start monit service
  service:
    name: monit
    enabled: yes
    state: started
  when: monit_init_start|bool

- name: Stop monit service
  service:
    name: monit
    enabled: yes
    state: stopped
  when: not monit_init_start|bool
