---
- name: Check if monit log file exists
  stat: 
    path: /var/log/monit.log
  register: log_file

- name: Ensure required monit dirs exists
  file:
    path: "{{ item.path }}"
    state: "{{ item.state }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
  when: item.when | d(true)
  with_items:
    - path: /var/log/monit.log
      state: file
      mode: '0644'
    - path: /etc/monit
      state: directory
      mode: '0755'
      when: ansible_os_family != "RedHat"
    - path: "{{ monit_path_confd }}"
      state: directory
      mode: '0755'
    - path: /var/lib/monit
      state: directory
      mode: '0755'

- name: Copy init script
  copy:
    src: monit-init
    dest: /etc/init.d/monit
    owner: root
    group: root
    mode: '0755'
  when: ansible_os_family != 'RedHat'

- name: Copy monit defaults file
  copy:
    src: monit
    dest: /etc/default/monit
    owner: root
    group: root
    mode: '0644'
  notify: monit reload

- name: Setup main monit conf file
  template:
    src: monitrc.j2
    dest: "{{ monit_path_main_cfg }}"
    owner: root
    group: root
    mode: '0600'
  notify: monit reload

- name: Enable monit service
  service:
    name: monit
    enabled: yes
    state: started
